### ISSUE TITLE
Fields lose focus too quickly

### ISSUE THREAD

**Issue by laurensvalk** [mit-cml/workspace-multiselect#22] opened 2023-08-15 09:37 UTC
I tried this on Blockly 10.1.2 and multiselect 0.1.7 to pull in all the latest fixes. Apologies if a fix for this was already in progress.

### Plugin enabled, fields lose focus

When releasing or moving the mouse, focus on a field is lost. This makes it quite hard to type anything in a field:

https://github.com/mit-cml/workspace-multiselect/assets/12326241/6cc43c69-48af-4381-9f6d-bec9ae099977

### Plugin disabled, fields maintain focus, normal behavior

https://github.com/mit-cml/workspace-multiselect/assets/12326241/49417dfc-b73d-4402-87d6-54aace42b74a

**Comment by HollowMan6** [comment] 2023-08-15 12:05
That looks like to be a side effect caused by the autofocus of the workspace https://github.com/mit-cml/workspace-multiselect/pull/19/commits/0ac0ec1f76227a2dc0389d8e5f1e80190f72e762 Will try to check if we can fix that, if not, then we will revert that.

**Comment by HollowMan6** [comment] 2023-08-15 15:59
Fixed in https://github.com/mit-cml/workspace-multiselect/pull/21/commits/9893cc401084e9e992e55d26503876297ad03c6c Hope workspace autofocus won't cause too much trouble.

**Closed** 2023-08-30 01:08 UTC
