### ISSUE TITLE
Problem with multi-select mode using rectangle drag to select

### ISSUE THREAD

**Issue by mark-friedman** [mit-cml/workspace-multiselect#63] opened 2024-06-27 23:14 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you are in multi-select mode and drag a rectangle in order to select multiple blocks, clicking on one of the selected blocks will then cause that block to get deselected. Note that using shift-clicks to select multiple blocks does not have that behavior.

### Reproduction steps

1. 
2. 
3.

**Comment by changminbark** [comment] 2024-06-28 02:45
What is supposed to be the intended behavior?

**Comment by HollowMan6** [comment] 2024-06-28 04:31
Did you reproduce this in main? I think this has already been fixed in https://github.com/mit-cml/workspace-multiselect/commit/230e9f6420537a1e51c4bd4220d12704c3aaee0c

**Comment by HollowMan6** [comment] 2024-06-28 04:46
> What is supposed to be the intended behavior?

"clicking on one of the selected blocks will then cause that block to get deselected" should be the expected one. Check README User behavior No.3.

> Note that using shift-clicks to select multiple blocks does not have that behavior.

I don't think I can reproduce this.

**Comment by mark-friedman** [comment] 2024-06-28 19:47
> > What is supposed to be the intended behavior?
> 
> "clicking on one of the selected blocks will then cause that block to get deselected" should be the expected one. Check README User behavior No.3.

User behavior no. 3 is about shift-click.  I'm referring to a plain click after the multi-select.  

> 
> > Note that using shift-clicks to select multiple blocks does not have that behavior.
> 
> I don't think I can reproduce this in the main branch. What version are you currently using? I think this has already been fixed in [230e9f6](https://github.com/mit-cml/workspace-multiselect/commit/230e9f6420537a1e51c4bd4220d12704c3aaee0c)

You can see the behavior at https://hollowman6.github.io/workspace-multiselect/.  I verified that that commit is in the source for that link. Try, for example, to do a multi-field update on a set of blocks selected via a rectangle drag.

**Comment by HollowMan6** [comment] 2024-06-28 20:03
> I'm referring to a plain click after the multi-select.

> You can see the behavior at https://hollowman6.github.io/workspace-multiselect/. I verified that that commit is in the source for that link. Try, for example, to do a multi-field update on a set of blocks selected via a rectangle drag.

Hmm, no luck for reproduction, any screenshot for this?

![GIF 2024-6-28 23-01-27](https://github.com/mit-cml/workspace-multiselect/assets/43995067/24064eae-e78e-4e89-959b-4ec1d3ce9137)
![GIF 2024-6-28 23-02-25](https://github.com/mit-cml/workspace-multiselect/assets/43995067/bed2c205-a6dc-4d20-b55d-117e588e5d7f)

**Comment by mark-friedman** [comment] 2024-06-28 20:17
> Hmm, no luck for reproduction, any video/GIF for this?

Ah, the difference is that I didn't explicitly turn off multi-select mode (i.e. didn't click the check mark) before trying the multi-field update.  If you ask me, the current behavior is a bit unintuitive and suboptimal.  Since we already document shift-click to unselect, why have plan click also deselecting?  It would make things simpler for the end-user, I think, to not require clicking the check mark in this situation.  Would it make things inconsistent somewhere else if we changed how this works?

**Comment by HollowMan6** [comment] 2024-06-28 20:31
I'm not sure if you are referring to this one:

![GIF 2024-6-28 23-11-34](https://github.com/mit-cml/workspace-multiselect/assets/43995067/5fde787c-edf0-4bcd-bf34-8ef61584022a)

This is actually somewhat expected, since we are still in multi-select mode, when you click on the text input field, the click event first de-select the block, then the edit cause us to exit the multi-select mode automatically.

> If you ask me, the current behavior is a bit unintuitive and suboptimal. Since we already document shift-click to unselect, why have plan click also deselecting?

Then how should we allow users to deselect the already selected block one by one, instead of deselect everything all together?

> It would make things simpler for the end-user, I think, to not require clicking the check mark in this situation. Would it make things inconsistent somewhere else if we changed how this works?

I'm not quite sure about what to change. The check-mark is optional if you are using keyboard, you just use the shift key and you don't need to care about the check-mark icon, we will be in multi-select mode when you keep holding the shift key. That check mark icon was designed to facilitate end-devices which don't have an actual keyboard (e.g. mobile phones) https://github.com/mit-cml/workspace-multiselect?tab=readme-ov-file#user-behavior See No.6 here. For mobile devices, that's unfortunately needed for them to exit multi-select mode manually by clicking on the icon.

**Comment by HollowMan6** [comment] 2024-06-28 20:36
> the click event first de-select the block, then the edit cause us to exit the multi-select mode automatically.

Although it might be possible for us to ignore the de-select here, it's more about the order of event to handle, I'll check.

**Comment by mark-friedman** [comment] 2024-06-28 21:01
> I'm not sure if you are referring to this one:
> 
> ![GIF 2024-6-28 23-11-34](https://private-user-images.githubusercontent.com/43995067/344306843-5fde787c-edf0-4bcd-bf34-8ef61584022a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MDc4NDAsIm5iZiI6MTcxOTYwNzU0MCwicGF0aCI6Ii80Mzk5NTA2Ny8zNDQzMDY4NDMtNWZkZTc4N2MtZWRmMC00YmNkLWJmMzQtOGVmNjE1ODQwMjJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDIwNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YTgxNDQxODRjNjIzOTY1MmJhMGM4Y2QyNjY3MTU3NGQxZGVlZjRjZTg0M2EwMTM0ZTVlYzYzYTA5NWZkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ai0s3iR27-lNn86-Zd3C5u5sXhI-YrWDRlJQ7ezHTfM) [ ![GIF 2024-6-28 23-11-34](https://private-user-images.githubusercontent.com/43995067/344306843-5fde787c-edf0-4bcd-bf34-8ef61584022a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MDc4NDAsIm5iZiI6MTcxOTYwNzU0MCwicGF0aCI6Ii80Mzk5NTA2Ny8zNDQzMDY4NDMtNWZkZTc4N2MtZWRmMC00YmNkLWJmMzQtOGVmNjE1ODQwMjJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDIwNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YTgxNDQxODRjNjIzOTY1MmJhMGM4Y2QyNjY3MTU3NGQxZGVlZjRjZTg0M2EwMTM0ZTVlYzYzYTA5NWZkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ai0s3iR27-lNn86-Zd3C5u5sXhI-YrWDRlJQ7ezHTfM) ](https://private-user-images.githubusercontent.com/43995067/344306843-5fde787c-edf0-4bcd-bf34-8ef61584022a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MDc4NDAsIm5iZiI6MTcxOTYwNzU0MCwicGF0aCI6Ii80Mzk5NTA2Ny8zNDQzMDY4NDMtNWZkZTc4N2MtZWRmMC00YmNkLWJmMzQtOGVmNjE1ODQwMjJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDIwNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YTgxNDQxODRjNjIzOTY1MmJhMGM4Y2QyNjY3MTU3NGQxZGVlZjRjZTg0M2EwMTM0ZTVlYzYzYTA5NWZkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ai0s3iR27-lNn86-Zd3C5u5sXhI-YrWDRlJQ7ezHTfM) [ ](https://private-user-images.githubusercontent.com/43995067/344306843-5fde787c-edf0-4bcd-bf34-8ef61584022a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MDc4NDAsIm5iZiI6MTcxOTYwNzU0MCwicGF0aCI6Ii80Mzk5NTA2Ny8zNDQzMDY4NDMtNWZkZTc4N2MtZWRmMC00YmNkLWJmMzQtOGVmNjE1ODQwMjJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDIwNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YTgxNDQxODRjNjIzOTY1MmJhMGM4Y2QyNjY3MTU3NGQxZGVlZjRjZTg0M2EwMTM0ZTVlYzYzYTA5NWZkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ai0s3iR27-lNn86-Zd3C5u5sXhI-YrWDRlJQ7ezHTfM)
> 
> This is actually somewhat expected, since we are still in multi-select mode, when you click on the text input field, the click event first deselect the block, then the edit cause us to exit the multi-select mode automatically.

Yes, I'm questioning whether the click should de-select the block, since we already have (documented) shift-click to de-select the block.

> 
> > If you ask me, the current behavior is a bit unintuitive and suboptimal. Since we already document shift-click to unselect, why have plan click also deselecting?
> 
> Then how should we allow users to deselect the already selected block one by one, instead of deselect everything all together?

Shift-click, which is what the documentation says is the way to deselect.

> 
> > It would make things simpler for the end-user, I think, to not require clicking the check mark in this situation. Would it make things inconsistent somewhere else if we changed how this works?
> 
> I'm not quite sure about what to change. The check-mark is optional if you are using keyboard, you just use the shift key and you don't need to care about the check-mark icon, we will be in multi-select mode when you keep holding the shift key. That check mark icon was designed to facilitate end-devices which don't have an actual keyboard (e.g. mobile phones) https://github.com/mit-cml/workspace-multiselect?tab=readme-ov-file#user-behavior See No.6 here. For mobile devices, that's unfortunately needed for them to exit multi-select mode manually by clicking on the icon.

Ha, I didn't even realize that the check-mark is optional and that you can shift-click-drag to multi-select!  That seems to work as I expected.

**Comment by mark-friedman** [comment] 2024-06-28 21:02
> > the click event first de-select the block, then the edit cause us to exit the multi-select mode automatically.
> 
> Although it might be possible for us to ignore the de-select here, it's more about the order of event to handle, I'll check.

I think it's worth doing, if it's not too difficult.

**Closed** 2024-06-28 22:02 UTC
Labels: bug

**Comment by HollowMan6** [comment] 2024-06-28 22:13
> > Although it might be possible for us to ignore the de-select here, it's more about the order of event to handle, I'll check.
> 
> I think it's worth doing, if it's not too difficult.

Unfortunately, it's not that simple, since the click event is handled on the DragSelect library's side and we have no direct control over that, so I use a white list for the common field element, and revert the last unselected block if we have any: https://github.com/mit-cml/workspace-multiselect/commit/396f88ba1a97880624a1bc08e4965181d8a2fb86 If you need to extend that whitelist, feel free to add more there.

> Shift-click, which is what the documentation says is the way to deselect.

Actually, we just have multi-select mode on when we hold the Shift, all the clicks that happen when multi-select mode is on will be treated as deselect, there's no separate distinction between shift-click or plain click. That's why I said "Clicking on the button above the dustbin **is equivalent to** holding/releasing the SHIFT key"

**Comment by mark-friedman** [comment] 2024-06-28 22:18
> 396f88b

Thanks!

**Comment by mark-friedman** [comment] 2024-06-28 22:23
> [ ![GIF 2024-6-29 1-16-04](https://private-user-images.githubusercontent.com/43995067/344327750-6fb82818-a8fc-4ee2-9f25-d2dd8ea6ee52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MTMzMDksIm5iZiI6MTcxOTYxMzAwOSwicGF0aCI6Ii80Mzk5NTA2Ny8zNDQzMjc3NTAtNmZiODI4MTgtYThmYy00ZWUyLTlmMjUtZDJkZDhlYTZlZTUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDIyMTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMjE0N2FiZGMwMTAwMWQzMGUwZTBkZGYzZWQ0NzY0ZTQwOWRmNWM5ZjUzM2M5ZThjYWUyYjQ0YTFiYThmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EoulbwEqNOAKwoidzIWId4l-6Hk20ESRKavRwjZ0fWg) ](https://private-user-images.githubusercontent.com/43995067/344327750-6fb82818-a8fc-4ee2-9f25-d2dd8ea6ee52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MTMzMDksIm5iZiI6MTcxOTYxMzAwOSwicGF0aCI6Ii80Mzk5NTA2Ny8zNDQzMjc3NTAtNmZiODI4MTgtYThmYy00ZWUyLTlmMjUtZDJkZDhlYTZlZTUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDIyMTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMjE0N2FiZGMwMTAwMWQzMGUwZTBkZGYzZWQ0NzY0ZTQwOWRmNWM5ZjUzM2M5ZThjYWUyYjQ0YTFiYThmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EoulbwEqNOAKwoidzIWId4l-6Hk20ESRKavRwjZ0fWg) [ ](https://private-user-images.githubusercontent.com/43995067/344327750-6fb82818-a8fc-4ee2-9f25-d2dd8ea6ee52.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MTMzMDksIm5iZiI6MTcxOTYxMzAwOSwicGF0aCI6Ii80Mzk5NTA2Ny8zNDQzMjc3NTAtNmZiODI4MTgtYThmYy00ZWUyLTlmMjUtZDJkZDhlYTZlZTUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDIyMTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMjE0N2FiZGMwMTAwMWQzMGUwZTBkZGYzZWQ0NzY0ZTQwOWRmNWM5ZjUzM2M5ZThjYWUyYjQ0YTFiYThmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EoulbwEqNOAKwoidzIWId4l-6Hk20ESRKavRwjZ0fWg)
> 
> > Shift-click, which is what the documentation says is the way to deselect.
> 
> Actually, we just have multi-select mode on when we hold the Shift, all the clicks that happen when multi-select mode is on will be treated as deselect, there's no separate distinction between shift-click or plain click. That's why I said "Clicking on the button above the dustbin **is equivalent to** holding/releasing the SHIFT key"

Okay, I get it now.  We could probably make that a little clearer in the docs.  If I didn't understand it then there are probably others who won't get it either.  In any case, that's something for another day ;-)

**Comment by HollowMan6** [comment] 2024-06-28 22:31
> Okay, I get it now. We could probably make that a little clearer in the docs. If I didn't understand it then there are probably others who won't get it either. In any case, that's something for another day ;-)

That would of course be appreciated! those entries were written initially when I was brainstorming for the design of this plugin in 2022, so it's not that well-organized https://github.com/mit-cml/workspace-multiselect/pull/1#issue-1301519378 We definitely need to improve that later.
